### ISSUE TITLE
Add 301 redirect from old blog post url to new one

### ISSUE THREAD

**Issue by MilosNikolic** [magicalpuffin/PuffinSystems-Homepage#35]
Hi!

I found your blog post trough google about using Argon2 on Cloudflare, but the link in google is broken.
I found the new link by going to your blog and then clicking it there but I'd suggest adding 301 redirect:
https://mli.puffinsystems.com/blog/20240407 -> https://mli.puffinsystems.com/blog/lucia-auth-cloudflare-argon2

Very cool blog post and it would be cool to have the link working since it does rank high in the results:
![CleanShot 2024-10-23 at 11 49 58@2x](https://github.com/user-attachments/assets/9d4b6c19-eae8-4be3-98dd-b24e5118ccb4)

**Comment by magicalpuffin** [comment]
Thanks for bring this up, I had a reroute for old links but looks like a prerender setting broke it. It is fixed now:
https://github.com/magicalpuffin/mli-puffinsystems/pull/36
